version: '2.4'

services:
  server:
    image: server
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - /usr/src/app/node_modules
      - ./server:/app
      - ./coverage:/usr/src/app/coverage
    environment:
      - CI
