version: '3.8'

services:
  server:
    image: server
    build:
      context: ./server
      target: prod
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on: 
      - mongo

  mongo:
    image: mongo:4.4-bionic


