version: '2.4'

services:
  server:
    image: server
    build:
      context: ./server
      target: test
    ports:
      - "8080:8080"
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
      - ./coverage:/usr/src/app/coverage
    environment:
      - CI
  client:
    image: client
    build:
      context: ./client
      target: test
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    environment:
      - CI
