version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
      docker_layer_caching: false
    
    steps:
      - checkout

      - run:
          name: Run tests using docker-compose
          command: docker-compose -f docker-compose.test.yml up --build 

      - run:
          name: Push test coverage to codecov
          command: bash <(curl -s https://codecov.io/bash) 

workflows:
    server:
      jobs:
        - build
            