version: 2.1

orbs: 
  node: circleci/node@3.0.0

jobs:
  server:
    executor: node/default

    steps:
      - checkout
      - node/install-packages:
          app-dir: server
          override-ci-command: npm install
      - run: npm test

workflows:
    build-and-test:
      jobs:
        - server