version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
      docker_layer_caching: false
    
    steps:
      - checkout

      - run:
          name: "Build docker containers from docker-compose.test.yml"
          command: docker-compose -f docker-compose.test.yml up --build

      - codecov/upload:
          file: coverage/*.json
      
      

workflows:
    server:
      jobs:
        - build
            