version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
      docker_layer_caching: false
    
    steps:
      - checkout

      - run:
          name: "Build docker containers from docker-compose.test.yml"
          command: docker-compose -f docker-compose.test.yml up --build 
      - run:
          name: Print environment variables
          command: printenv
      - run:
          name: Push test result to codecov
          command: bash <(curl -s https://codecov.io/bash) 

workflows:
    server:
      jobs:
        - build
            