version: 2.1

orbs: 
  node: circleci/node@3.0.0

jobs:
  server:
    executor: node/default

    steps:
      - checkout
      - node/install-packages

workflows:
    build-and-test:
      jobs:
        - server