version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
      docker_layer_caching: true
    
    steps:
      - checkout

      - run:
          name: "Build docker containers from docker-compose.test.yml"
          command: docker-compose -f docker-compose.test.yml up --build
      

workflows:
    server:
      jobs:
        - build
            